#
# makefile for csc507 term 201 (spring 2019-2020)
#
# author: bjr
# created: 19 feb 2018
# last-update: 16 nov 2019
#

PY= python3

all-answers:
	-make rsa
	-make elgamal

rsa:
	${PY} rsa-tasks.py

elgamal:
	${PY} elgamal-tasks.py
